name: build_Release
on:
  push:
    branches:
      - 1.1.10
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - 1.1.10
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: '1.1.10'
  BUNDLEID: 'com.wwg135.Dopamine'
 
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Procursus
        uses: wwg135/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make
          
      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos
         
      - name: Pre Bundleid
        run: |
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./Packages/Fugu15KernelExploit/Sources/Fugu15KernelExploit/Util.swift
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./Dopamine/Dopamine/Dopamine.entitlements
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./Dopamine/Dopamine.xcodeproj/project.pbxproj
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./BaseBin/jailbreakd/src/update.m
     
      - name: Build and Install trustcache
        run: |
          set -x
          git clone https://github.com/CRKatri/trustcache
          cd trustcache
          gmake -j$(sysctl -n hw.physicalcpu) OPENSSL=1
          sudo cp trustcache /opt/procursus/bin/
          
      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "shT=$(TZ=UTC-8 date +'%Y-%m-%d'' ''%H:%M:%S')" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV
          
      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.shT }}
          echo ${{ env.logT }}
          
      - name: Pre code
        run: |
          sed -i '' "s/AAA/更新时间/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAB/${{ env.shT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAC/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
      
      - name: Pre body
        run: |
          echo -e "更新时间：${{ env.logT }}" >> body.txt
          echo -e "\n当前更新日志如下：" >> body.txt
          echo -e "\n> - 修复更新日志显示问题" >> body.txt
          echo -e "\n\nM哥修改版的功能：" >> body.txt
          echo -e "\n> - 1.非映射挂载+非桥接心浪版本（应用内支持OTA单独升级版本，不接收挂载版本升级）.\n> - 2.增加真皮底层屏蔽App越狱检测开关（首页点击“Dopamine”即显示/隐藏），感谢真皮大佬.\n> - 3.修改app标识符，可与官方版本共存.\n> - 4.增加重启、更新环境按钮（长按重启用户空间弹出），感谢liam0205大佬代码.\n> - 5.设置增加显示/隐藏式功能（点击设置里面的“成功率”，即可开启显示/隐藏）.\n> - 6.增加检查更新功能，以便开启/关闭OTA升级提示.\n> - 7.首页增加运行时间显示（点击首页开发者信息，即可显示/隐藏）.\n> - 8.增加自定义背景（首页长按背景即可，开关：从相册选择图片或者恢复默认）.\n> - 9.改变下载进度条，添加到首页下方.\n> - 10.设置增加“一键备份”功能，点击有详细说明。\n> - 11.增加“清除越狱”提示，避免越狱状态下清除越狱出现未知问题.\n> - 12.其他优化及新功能开发中，敬请期待..." >> body.txt
          echo -e "\n[点击当前版本下载](https://github.com/wwg135/Dopamine/releases/download/${{ env.msT }}/Dopamine.ipa)" >> body.txt
  
      - name: Build ipa
        run: |
          set -x
          export THEOS=$HOME/theos
          gmake -j$(sysctl -n hw.physicalcpu)
          mv Dopamine/Dopamine.tipa Dopamine.ipa
          
      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: 1.1.10
          body_path: body.txt
          prerelease: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
