name: build_Release
on:
  push:
    branches:
      - 1.1.5
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

env:
  VERSION: '1.1.5'
 
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Procursus
        uses: wwg135/procursus-action@main
        with:
          packages: ldid trustcache make findutils coreutils

      - name: Install THEOS
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos

      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "shT=$(TZ=UTC-8 date +'%Y-%m-%d'' ''%H:%M:%S')" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.shT }}
          echo ${{ env.logT }}

      - name: Pre code and keychain
        run: |
          sed -i '' "s/AAA/更新时间/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAB/${{ env.shT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sed -i '' "s/AAC/${{ env.msT }}/g" ./Dopamine/Dopamine/UI/Views/JailbreakView.swift
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
      
      - name: Pre body
        run: |
          echo -e "[点击当前版本下载](https://github.com/wwg135/Dopamine/releases/download/${{ env.msT }}/Dopamine.ipa)" >> body.txt
          echo -e "\n更新时间：${{ env.logT }}" >> body.txt
          echo -e "\n**当前更新日志如下：**" >> body.txt
          echo -e "\n> - 1.必看重点说明：当前版本无桥接心浪、无映射挂载、无预装pre，仅有基板Ellekit，谨慎安装！！\n> - 2.当前命名为稳定版本（只是命名而已，不是所谓的稳定），后续OTA只升级当前稳定版，不接收1.1.5开发版、1.0.5版本的OTA升级\n> - 3.更新日志只显示要更新版本的日志，提高启动多巴胺检测是否更新的效率！！！！！" >> body.txt
      
      - name: Build ipa
        run: |
          set -x
          export THEOS=$HOME/theos
          gmake -j$(sysctl -n hw.physicalcpu)
          mv Dopamine/Dopamine.tipa Dopamine.ipa

      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: 1.1.5 稳定版
          tag_name: ${{ env.msT }}
          target_commitish: 1.1.5-self
          body_path: body.txt
          prerelease: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
