name: Fork Sync

on:
  schedule:
    - cron: '0 7 * * *' # every day at 7 AM
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: wwg135
          base: main
          head: main
